import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#000' },
  arView: { flex: 1 },
  topGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 170,
  },
  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 240,
  },
  backBtn: {
    position: 'absolute',
    left: 16,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: 20,
    padding: 8,
  },

  // Searching
  searchingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 4,
    borderColor: 'rgba(255,248,231,0.82)',
    backgroundColor: 'rgba(124,58,237,0.12)',
    marginBottom: 18,
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 18,
    elevation: 4,
  },
  searchingCard: {
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginHorizontal: 28,
    borderWidth: 2,
    borderColor: 'rgba(255,154,46,0.35)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 16,
    elevation: 10,
  },
  searchingTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 20,
    color: colors.textDark,
    textAlign: 'center',
    marginBottom: 4,
  },
  searchingHint: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 15,
    color: colors.textMid,
    textAlign: 'center',
    lineHeight: 20,
  },
  rotateInstruction: {
    position: 'absolute',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(0,0,0,0.62)',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.32)',
  },
  rotateInstructionText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 15,
    color: '#FFFFFF',
  },

  // Placed
  placedOverlay: {
    position: 'absolute',
    bottom: 18,
    left: 18,
    right: 18,
    alignItems: 'center',
    gap: 7,
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderRadius: 22,
    paddingTop: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 12,
  },
  placedWord: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 30,
    color: colors.textDark,
  },
  placedLabel: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: colors.textMid,
    marginBottom: 4,
  },
  replaceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF0B8',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 11,
  },
  replaceBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: colors.primary,
  },

  // Timeout
  timeoutOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  timeoutCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 32,
  },
  timeoutTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: colors.textDark,
    textAlign: 'center',
  },
  timeoutSub: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 15,
    color: colors.textMid,
    textAlign: 'center',
    lineHeight: 22,
  },
  tryAgainBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingHorizontal: 28,
    paddingVertical: 12,
    marginTop: 4,
  },
  tryAgainText: { fontFamily: 'Fredoka-Bold', fontSize: 16, color: '#fff' },
  goBackText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 15,
    color: colors.textMid,
    paddingVertical: 8,
  },
});
