import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
  },
  centered: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 32,
  },
  backBtn: { padding: 8, alignSelf: 'flex-start' },
  // Card-shaped confirmation sheet — gives the screen a focused, modal
  // feeling instead of looking like a generic form.
  sheet: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 28,
    marginTop: 8,
    padding: 24,
    alignItems: 'stretch',
    gap: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 6,
  },
  heroWrap: {
    width: '100%',
    aspectRatio: 1.7,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: colors.primaryLight,
    marginBottom: 6,
  },
  heroImg: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 26,
    color: colors.textDark,
    textAlign: 'center',
  },
  packName: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 18,
    color: colors.textMid,
    textAlign: 'center',
    marginTop: -4,
  },
  // Price row reads like a checkout receipt — quiet label, bold figure.
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: '#EFE2C9',
    marginTop: 6,
  },
  priceLabel: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: colors.textMid,
  },
  priceValue: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: colors.textDark,
  },
  bullets: { gap: 8, marginTop: 6 },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bulletText: {
    fontFamily: 'Fredoka-Medium',
    fontSize: 14,
    color: colors.textDark,
    flex: 1,
  },
  simNotice: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 12,
    color: colors.textLight,
    textAlign: 'center',
    marginTop: 4,
  },
  errorText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: colors.error,
    textAlign: 'center',
  },
  ctaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 20,
    paddingVertical: 16,
    marginTop: 4,
  },
  ctaDisabled: { opacity: 0.5 },
  ctaText: { fontFamily: 'Fredoka-Bold', fontSize: 18, color: '#fff' },
  cancelBtn: { alignItems: 'center', paddingVertical: 10 },
  cancelText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: colors.textMid,
  },
  successTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: colors.textDark,
    textAlign: 'center',
  },
  successSub: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: colors.textMid,
    textAlign: 'center',
  },
});
