import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 20,
    gap: 8,
  },
  backBtn: { padding: 8, width: 44 },
  packName: {
    flex: 1,
    textAlign: "center",
    fontFamily: "Fredoka-Bold",
    fontSize: 24,
    color: "#FFF",
  },
  body: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 16, gap: 10 },
  wordRow: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  wordDot: { width: 10, height: 10, borderRadius: 5 },
  wordLabel: {
    fontFamily: "Fredoka-Bold",
    fontSize: 18,
    color: colors.textDark,
    flex: 1,
  },
  wordSyllables: {
    fontFamily: "Fredoka-Regular",
    fontSize: 13,
    color: colors.textMid,
  },
  // Premium lock card
  lockCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 28,
    margin: 16,
    padding: 28,
    alignItems: "center",
    gap: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
  },
  lockTitle: {
    fontFamily: "Fredoka-Bold",
    fontSize: 24,
    color: colors.textDark,
    textAlign: "center",
  },
  lockBody: {
    fontFamily: "Fredoka-Regular",
    fontSize: 15,
    color: colors.textMid,
    textAlign: "center",
    lineHeight: 22,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
    marginTop: 4,
  },
  chip: {
    backgroundColor: "#EDE9FE",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipText: {
    fontFamily: "Fredoka-SemiBold",
    fontSize: 13,
    color: colors.primary,
  },
  unlockBtn: {
    borderRadius: 32,
    paddingHorizontal: 32,
    paddingVertical: 14,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  unlockBtnText: { fontFamily: "Fredoka-Bold", fontSize: 18, color: "#FFF" },
  comingSoon: {
    fontFamily: "Fredoka-Regular",
    fontSize: 13,
    color: colors.textMid,
    marginTop: 4,
  },
  ctaWrap: { marginHorizontal: 16, marginBottom: 32, marginTop: 8 },
});
