import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  topGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 170,
  },
  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 260,
  },

  // Header overlay
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Fredoka-Bold',
    fontSize: 18,
    color: '#FFFFFF',
    marginHorizontal: 8,
  },
  headerSpacer: { width: 40 },

  // Bottom info card
  bottomCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 30,
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
  },
  wordName: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 30,
    color: '#3D2008',
  },
  packLabel: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 12,
    color: '#C96B00',
    backgroundColor: '#FFF0B8',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  syllableRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  syllableChip: {
    backgroundColor: '#EDE9FE',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  syllableText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 15,
    color: '#5B2DC0',
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
    marginTop: 2,
  },
  navBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F0EBFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navBtnDisabled: { opacity: 0.35 },
  navCounter: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: '#9B87CC',
    minWidth: 60,
    textAlign: 'center',
  },
  factBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    backgroundColor: '#FFF0B8',
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 11,
    width: '100%',
  },
  factText: {
    flex: 1,
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: '#3B210F',
    lineHeight: 20,
  },

  // Loading cover
  loadingCover: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: '#FFFFFF',
  },
  slowCard: {
    width: '86%',
    backgroundColor: 'rgba(255,248,231,0.97)',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  slowTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: '#3D2008',
    textAlign: 'center',
  },
  slowBody: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 15,
    color: '#7A4A1A',
    textAlign: 'center',
    lineHeight: 21,
  },
  slowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  slowNavBtn: {
    borderRadius: 16,
    backgroundColor: '#FFF0B8',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  slowNavText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 13,
    color: '#7A4A1A',
  },
  tryAgainBtn: {
    borderRadius: 18,
    backgroundColor: '#FF9A2E',
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  tryAgainText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  reportSentText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: '#059669',
    backgroundColor: '#D1FAE5',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
});
