import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  bg: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 20,
    gap: 8,
  },
  backBtn: { padding: 8, width: 44 },
  packName: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: '#FFF',
  },
  body: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 16, gap: 10 },
  wordRow: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  wordDot: { width: 10, height: 10, borderRadius: 5 },
  wordLabel: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: colors.textDark,
    flex: 1,
  },
  wordSinhala: {
    fontFamily: 'Maname-Regular',
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 1,
  },
  wordSyllables: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: colors.textMid,
  },
  // Premium lock scroll — no extra padding on the sides, the card and hero
  // handle their own margin so the hero can sit flush against the card.
  lockScroll: { paddingTop: 16, gap: 0 },
  // Hero wrapper for the lock branch — holds the cover art + floating lock
  // chip. 16:10ish aspect so the image reads as a poster, not a tile.
  lockHeroWrap: {
    marginHorizontal: 16,
    borderRadius: 24,
    overflow: 'hidden',
    aspectRatio: 1.5,
    backgroundColor: colors.primaryLight,
  },
  lockHeroImg: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Floating "Locked" chip in top-right of hero — small enough not to
  // overpower the art but always visible.
  lockChip: {
    position: 'absolute',
    top: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  lockChipText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 12,
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  // Lock card — sits below the hero, holds the value pills + CTA.
  lockCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 28,
    margin: 16,
    padding: 24,
    alignItems: 'center',
    gap: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
  },
  lockTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: colors.textDark,
    textAlign: 'center',
  },
  lockBody: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: colors.textMid,
    textAlign: 'center',
    lineHeight: 22,
  },
  // Three-column value-prop row — bullets the appeal without burying it in
  // a paragraph. Each pill is flex:1 so they fill the card evenly.
  pillRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    width: '100%',
  },
  valuePill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 14,
    backgroundColor: '#FFF8E7',
    borderWidth: 1,
    borderColor: '#EFE2C9',
  },
  valuePillText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 11,
    color: colors.textDark,
    flex: 1,
  },
  lockWordsLabel: {
    marginTop: 8,
  },
  lockWordsLabelText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 13,
    color: colors.textMid,
    letterSpacing: 0.5,
  },
  unlockHint: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 13,
    color: colors.textMid,
    marginTop: 4,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginTop: 4,
  },
  chip: {
    backgroundColor: '#EDE9FE',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: colors.primary,
  },
  unlockBtn: {
    borderRadius: 32,
    paddingHorizontal: 32,
    paddingVertical: 14,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  unlockBtnText: { fontFamily: 'Fredoka-Bold', fontSize: 22, color: '#FFF' },
  comingSoon: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: colors.textMid,
    marginTop: 4,
  },
  ctaWrap: { marginHorizontal: 16, marginBottom: 32, marginTop: 8 },
});
