import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0EBFF' },
  safeArea: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20 },
  headerTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: '#1A1050',
    marginBottom: 20,
  },
  avatarCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#5B2DC0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#5B2DC0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  avatarText: { fontFamily: 'Fredoka-Bold', fontSize: 28, color: '#FFF' },
  displayName: { fontFamily: 'Fredoka-Bold', fontSize: 22, color: '#1A1050', marginBottom: 4 },
  email: { fontFamily: 'Fredoka-Regular', fontSize: 14, color: '#888', marginBottom: 12 },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 4,
  },
  streakEmoji: { fontSize: 16 },
  streakText: { fontFamily: 'Fredoka-SemiBold', fontSize: 14, color: '#E65100' },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  statCard: {
    flex: 1,
    backgroundColor: '#E8E0FF',
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: 'center',
  },
  statNumber: { fontFamily: 'Fredoka-Bold', fontSize: 28, color: '#5B2DC0' },
  statLabel: { fontFamily: 'Fredoka-Regular', fontSize: 12, color: '#7B6EA6', marginTop: 2, textAlign: 'center' },
  parentDashBtn: {
    backgroundColor: '#EDE9FF',
    borderRadius: 40,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: '#5B2DC0',
  },
  parentDashText: { fontFamily: 'Fredoka-Bold', fontSize: 18, color: '#5B2DC0' },
  signOutBtn: {
    backgroundColor: '#1A1050',
    borderRadius: 40,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  signOutText: { fontFamily: 'Fredoka-Bold', fontSize: 18, color: '#FFF', letterSpacing: 0.5 },
});
