import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20 },
  headerTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 34,
    color: colors.textDark,
    marginBottom: 20,
  },
  avatarCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#5C3317',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 8,
  },
  displayName: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 26,
    color: colors.textDark,
    marginBottom: 4,
  },
  email: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 17,
    color: colors.textMid,
    marginBottom: 12,
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 4,
  },
  streakText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 17,
    color: '#E65100',
  },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
  statCard: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    borderRadius: 20,
    paddingVertical: 18,
    alignItems: 'center',
    gap: 4,
  },
  statNumber: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 32,
    color: colors.primary,
  },
  statLabel: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 15,
    color: colors.textMid,
    textAlign: 'center',
  },
  parentDashBtn: {
    backgroundColor: colors.backgroundLight,
    borderRadius: 40,
    paddingVertical: 18,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  parentDashText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 20,
    color: colors.primary,
  },
  signOutBtn: {
    backgroundColor: colors.primaryDark,
    borderRadius: 40,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 4,
  },
  signOutText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 20,
    color: '#FFF',
    letterSpacing: 0.5,
  },
});
