import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20 },
  headerTitle: {
    fontFamily: "Fredoka-Bold",
    fontSize: 28,
    color: colors.textDark,
    marginBottom: 20,
  },
  avatarCard: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  avatarText: { fontFamily: "Fredoka-Bold", fontSize: 28, color: "#FFF" },
  displayName: {
    fontFamily: "Fredoka-Bold",
    fontSize: 22,
    color: colors.textDark,
    marginBottom: 4,
  },
  email: {
    fontFamily: "Fredoka-Regular",
    fontSize: 14,
    color: colors.textMid,
    marginBottom: 12,
  },
  streakBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF3E0",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 4,
  },
  streakEmoji: { fontSize: 16 },
  streakText: {
    fontFamily: "Fredoka-SemiBold",
    fontSize: 14,
    color: "#E65100",
  },
  statsRow: { flexDirection: "row", gap: 12, marginBottom: 24 },
  statCard: {
    flex: 1,
    backgroundColor: colors.backgroundCard,
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: "center",
  },
  statNumber: {
    fontFamily: "Fredoka-Bold",
    fontSize: 28,
    color: colors.primary,
  },
  statLabel: {
    fontFamily: "Fredoka-Regular",
    fontSize: 12,
    color: colors.textMid,
    marginTop: 2,
    textAlign: "center",
  },
  parentDashBtn: {
    backgroundColor: colors.backgroundLight,
    borderRadius: 40,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  parentDashText: {
    fontFamily: "Fredoka-Bold",
    fontSize: 18,
    color: colors.primary,
  },
  signOutBtn: {
    backgroundColor: colors.primaryDark,
    borderRadius: 40,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 4,
  },
  signOutText: {
    fontFamily: "Fredoka-Bold",
    fontSize: 18,
    color: "#FFF",
    letterSpacing: 0.5,
  },
});
