import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 20,
    gap: 8,
  },
  backBtn: { padding: 8, width: 44 },
  headerCenter: { flex: 1, alignItems: "center" },
  title: { fontFamily: "Fredoka-Bold", fontSize: 28, color: colors.textDark },
  subtitle: { fontFamily: "Fredoka-Regular", fontSize: 16, color: colors.textMid },
  tabsWrapper: { paddingHorizontal: 16 },
  tabs: {
    flexDirection: "row",
    backgroundColor: colors.backgroundLight,
    borderRadius: 16,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  tabActive: { backgroundColor: colors.primary },
  tabText: { fontFamily: "Fredoka-SemiBold", fontSize: 17, color: colors.textMid },
  tabTextActive: { color: "#FFF" },
  scroll: { paddingHorizontal: 16, paddingTop: 12, gap: 12 },
  card: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  wishCard: {
    backgroundColor: colors.backgroundCard,
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: colors.primaryLight,
    shadowOpacity: 0,
    elevation: 0,
  },
  emojiCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.backgroundLight,
    alignItems: "center",
    justifyContent: "center",
  },
  wishEmojiCircle: { backgroundColor: "#FEF3C7" },
  cardBody: { flex: 1, gap: 4 },
  wordText: { fontFamily: "Fredoka-Bold", fontSize: 22, color: colors.textDark },
  dateText: { fontFamily: "Fredoka-Regular", fontSize: 15, color: "#94A3B8" },
  arBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  arBtnText: { fontFamily: "Fredoka-SemiBold", fontSize: 16, color: "#FFF" },
  trashBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyLottie: { width: 160, height: 160 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 },
  emptyTitle: { fontFamily: "Fredoka-Bold", fontSize: 26, color: colors.textDark },
  emptySub: {
    fontFamily: "Fredoka-Regular",
    fontSize: 18,
    color: colors.textMid,
    textAlign: "center",
    paddingHorizontal: 40,
  },
});
