import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  arView: { flex: 1 },

  noCamera: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#0d0d0d',
  },
  noCameraText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    paddingHorizontal: 32,
  },

  // Both HUD buttons: same dark circle, white icon
  backButton: {
    position: 'absolute',
    top: 56,
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetButton: {
    position: 'absolute',
    top: 56,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  packBadge: {
    position: 'absolute',
    top: 56,
    alignSelf: 'center',
    left: '50%',
    transform: [{ translateX: -70 }],
    backgroundColor: 'rgba(91,45,192,0.85)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  packBadgeText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: '#fff',
  },

  statusBar: {
    position: 'absolute',
    top: 136,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(91,45,192,0.82)',
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingVertical: 13,
    borderWidth: 1.5,
    borderColor: 'rgba(167,139,250,0.55)',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 18,
    elevation: 10,
  },
  statusDotWrapper: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusDotRing: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(74,222,128,0.25)',
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#4ADE80',
  },
  statusText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 26,
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textShadowColor: '#A78BFA',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },

  // Bottom sheet — 15-20% shorter via tighter padding and spacing
  resultCard: {
    position: 'absolute',
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: colors.backgroundCard,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    shadowColor: '#C4A060',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
  },
  // Polished drag handle
  resultCardHandle: {
    width: 48,
    height: 5,
    borderRadius: 100,
    backgroundColor: colors.handleBar,
    opacity: 0.7,
    alignSelf: 'center',
    marginBottom: 12,
  },
  // Title row: emoji + word block side by side
  resultCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  wordEmoji: {
    fontSize: 32,
    lineHeight: 38,
  },
  resultWordBlock: { flex: 1 },
  resultWord: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: colors.textDark,
  },
  sinhalaLabel: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  resultPack: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 13,
    color: colors.textMid,
    marginTop: 1,
  },
  // Fact box: warmer yellow, dark brown text, breathing room
  factBox: {
    flexDirection: 'row',
    backgroundColor: colors.factBoxBg,
    borderRadius: 20,
    padding: 14,
    gap: 10,
    marginTop: 2,
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  factIcon: {
    marginTop: 2,
  },
  factText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: colors.textFact,
    flex: 1,
    lineHeight: 22,
  },
  // Action row: [X] [Place Word — primary] [Save — secondary]
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dismissBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Place = primary orange button, fills remaining width
  placeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 22,
  },
  placeBtnText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 16,
    color: '#FFF',
  },
  // Save = secondary outlined button
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderPrimary,
  },
  saveBtnDisabled: {
    backgroundColor: '#FFF3DC',
    borderColor: 'transparent',
    opacity: 0.5,
  },
  saveBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: colors.primary,
  },
  saveBtnTextDisabled: {
    color: colors.primary,
  },

  unknownChip: {
    position: 'absolute',
    bottom: 160,
    alignSelf: 'center',
    backgroundColor: 'rgba(20,10,50,0.88)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.4)',
    maxWidth: '90%',
  },
  unknownChipText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: '#C4B5FD',
    flexShrink: 1,
  },
  unknownWord: {
    fontFamily: 'Fredoka-Bold',
    color: '#FFFFFF',
  },
  wishBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  wishBtnDone: {
    backgroundColor: '#059669',
  },
  wishBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 13,
    color: '#FFF',
  },
  confettiAnim: {
    position: 'absolute',
    top: -50,
    alignSelf: 'center',
    width: 300,
    height: 200,
  },
});
