import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  arView: { flex: 1 },
  previewTopGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 180,
  },
  previewBottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 260,
  },

  noCamera: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#0d0d0d',
  },
  noCameraText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: 'rgba(255,255,255,0.4)',
    textAlign: 'center',
    paddingHorizontal: 32,
  },

  // Both HUD buttons: same dark circle, white icon
  backButton: {
    position: 'absolute',
    top: 56,
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetButton: {
    position: 'absolute',
    top: 56,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  packBadge: {
    position: 'absolute',
    top: 56,
    alignSelf: 'center',
    left: '50%',
    transform: [{ translateX: -70 }],
    backgroundColor: 'rgba(91,45,192,0.85)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  packBadgeText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: '#fff',
  },

  scanInstructionCard: {
    position: 'absolute',
    top: 116,
    alignSelf: 'center',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,154,46,0.35)',
    shadowColor: '#2B164F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 10,
  },
  scanStepBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scanStepText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 13,
    color: colors.primaryDark,
    textTransform: 'uppercase',
  },
  statusDotWrapper: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusDotRing: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(255,154,46,0.25)',
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  scanInstructionText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 20,
    color: colors.textDark,
    textAlign: 'center',
  },

  // Bottom sheet — 15-20% shorter via tighter padding and spacing
  resultCard: {
    position: 'absolute',
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
    shadowColor: '#C4A060',
    shadowOffset: { width: 0, height: -2 },
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowOpacity: 0.24,
    shadowRadius: 20,
    elevation: 12,
  },
  // Polished drag handle
  resultCardHandle: {
    width: 48,
    height: 5,
    borderRadius: 100,
    backgroundColor: colors.handleBar,
    opacity: 0.7,
    alignSelf: 'center',
    marginBottom: 12,
  },
  // Title row: emoji + word block side by side
  resultCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  wordEmoji: {
    fontSize: 32,
    lineHeight: 38,
  },
  resultWordBlock: { flex: 1 },
  resultWord: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 28,
    color: colors.textDark,
  },
  sinhalaLabel: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  resultPack: {
    alignSelf: 'flex-start',
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 12,
    color: colors.primaryDark,
    marginTop: 1,
    backgroundColor: '#FFF0B8',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  // Fact box: warmer yellow, dark brown text, breathing room
  factBox: {
    flexDirection: 'row',
    backgroundColor: colors.factBoxBg,
    borderRadius: 20,
    padding: 14,
    gap: 10,
    marginTop: 2,
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  factIcon: {
    marginTop: 2,
  },
  factText: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 14,
    color: colors.textFact,
    flex: 1,
    lineHeight: 22,
  },
  // Action row: [X] [Place Word — primary] [Save — secondary]
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dismissBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Place = primary orange button, fills remaining width
  placeBtn: {
    flex: 1.35,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 22,
  },
  placeBtnDisabled: {
    backgroundColor: 'rgba(122,74,26,0.35)',
  },
  placeBtnText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 16,
    color: '#FFF',
  },
  // Save = secondary outlined button
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderPrimary,
  },
  saveBtnDisabled: {
    backgroundColor: '#FFF3DC',
    borderColor: 'transparent',
    opacity: 0.5,
  },
  saveBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: colors.primary,
  },
  saveBtnTextDisabled: {
    color: colors.primary,
  },

  unknownCard: {
    position: 'absolute',
    bottom: 128,
    alignSelf: 'center',
    backgroundColor: 'rgba(255,248,231,0.96)',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,154,46,0.35)',
    maxWidth: '90%',
    shadowColor: '#2B164F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 16,
    elevation: 10,
  },
  unknownIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFF0B8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unknownCardText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: colors.textDark,
    flexShrink: 1,
    lineHeight: 21,
  },
  wishBtn: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  wishBtnDone: {
    backgroundColor: '#059669',
  },
  wishBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 14,
    color: '#FFF',
  },
  confettiAnim: {
    position: 'absolute',
    top: -50,
    alignSelf: 'center',
    width: 300,
    height: 200,
  },
});
