import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: { paddingHorizontal: 16, gap: 10 },
  sectionLabel: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 12,
    color: colors.textMid,
    letterSpacing: 1,
    marginTop: 6,
    marginLeft: 4,
  },
  card: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#5C3317',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  usageCard: { flexDirection: 'row', alignItems: 'center' },
  usageLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  usageIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF0DC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  usageValue: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 32,
    color: colors.textDark,
    lineHeight: 36,
  },
  usageUnit: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 20,
    color: colors.textMid,
  },
  usageSub: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 13,
    color: colors.textMid,
  },
  clockImg: { width: 80, height: 80, marginRight: -4 },
  limitRow: { flexDirection: 'row', alignItems: 'center' },
  stepBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepBtnDisabled: { opacity: 0.3 },
  stepBtnText: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: colors.primary,
    lineHeight: 26,
  },
  limitValue: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 17,
    color: colors.textDark,
  },
  setBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  setBtnSaved: { backgroundColor: '#F5C070' },
  setBtnIcon: { marginBottom: 1 },
  setBtnText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 16,
    color: colors.white,
  },
  timedRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  timedIcon: { width: 48, height: 48 },
  timedText: { flex: 1 },
  timedLabel: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 15,
    color: colors.textDark,
  },
  timedSub: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 12,
    color: colors.textMid,
    marginTop: 2,
  },
});
