import { StyleSheet } from "react-native";
import { colors } from "../../constants/colors";

export const styles = StyleSheet.create({
  card: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFF9C4",
    borderRadius: 32,
    padding: 18,
    minHeight: 96,
    overflow: "hidden",
    shadowColor: colors.accentAmber,
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 8,
  },
  cardFound: { backgroundColor: "#D1FAE5" },
  sheen: { borderRadius: 32 },
  s1: { position: "absolute", top: 14, left: "42%" },
  s2: { position: "absolute", top: 32, left: "58%" },
  s3: { position: "absolute", bottom: 16, left: "50%" },
  s4: { position: "absolute", bottom: 10, left: "68%" },
  left: { flex: 1, gap: 4 },
  speakerRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  label: {
    fontFamily: "Fredoka-Regular",
    fontSize: 14,
    color: colors.textMid,
    letterSpacing: 0.3,
  },
  word: {
    fontFamily: "Fredoka-Bold",
    fontSize: 32,
    color: colors.textDark,
  },
  doneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  doneText: {
    fontFamily: "Fredoka-SemiBold",
    fontSize: 16,
    color: colors.successDark,
  },
  scanBtnShadow: {
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  scanBtnOuter: { borderRadius: 20, padding: 2, backgroundColor: "#5C3317" },
  scanBtnInner: { borderRadius: 18, padding: 1.5, backgroundColor: "#C48A4A" },
  scanBtnContent: {
    borderRadius: 16,
    width: 68,
    paddingVertical: 12,
    alignItems: "center",
    gap: 4,
    overflow: "hidden",
  },
  scanBtnText: {
    fontFamily: "Fredoka-Bold",
    fontSize: 15,
    color: "#FFF",
  },
  checkCircle: { paddingLeft: 8 },
  flipAnim: { width: 64, height: 64 },
});
