import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: { gap: 16, paddingHorizontal: 16 },
  // logoRow is the centered WoodenSign band; the mute toggle floats over its
  // left edge as an absolute overlay so it doesn't shift the sign off-centre.
  logoRow: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
    marginTop: 5,
  },
  // White disc with a soft drop shadow — readable against the parallax sky
  // background and visually weighted enough to feel like a primary control.
  muteButton: {
    position: 'absolute',
    left: 4,
    top: '50%',
    marginTop: -22,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3D2008',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(196,138,74,0.35)',
  },

  headerCard: {
    borderRadius: 28,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 22,
    elevation: 10,
  },
  headerSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '45%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  deco1: { position: 'absolute', top: 12, right: 54 },
  deco2: { position: 'absolute', top: 28, right: 36 },
  deco3: { position: 'absolute', bottom: 14, left: 110 },
  deco4: { position: 'absolute', bottom: 20, right: 60 },
  deco5: { position: 'absolute', top: 42, left: 90 },

  mascotCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  greetingBlock: { flex: 1, gap: 2 },
  greeting: { fontFamily: 'Fredoka-Bold', fontSize: 28, color: '#FFF' },
  subGreeting: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 10,
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  streakText: { fontFamily: 'Fredoka-Bold', fontSize: 15, color: '#FFF' },

  // Trophy entry point — sits in the welcome banner. A high-contrast white
  // disc + amber glyph + "Trophies" label is much more readable than the
  // previous low-opacity yellow circle, which blended into the orange card.
  trophyWrap: { alignItems: 'center', gap: 4, padding: 4 },
  trophyCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFD16B',
    shadowColor: '#7A3D00',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.28,
    shadowRadius: 6,
    elevation: 5,
  },
  trophyLabel: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 11,
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },

  progressBanner: {
    backgroundColor: colors.backgroundCard,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#C96B00',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  progressLeft: { flex: 1, gap: 6 },
  gemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  gem: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gemMore: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 18,
    color: colors.textMid,
    marginLeft: 2,
  },
  progressCount: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 22,
    color: '#3D1800',
    lineHeight: 26,
  },
  progressSub: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 15,
    color: colors.textMid,
    marginBottom: 4,
  },
  progressTrack: {
    height: 14,
    borderRadius: 7,
    backgroundColor: 'rgba(255,154,46,0.15)',
    overflow: 'hidden',
  },
  progressFill: {
    height: 14,
    borderRadius: 7,
  },
  chevronCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.backgroundCard,
    borderWidth: 2,
    borderColor: 'rgba(255,154,46,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF9A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },

  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  sectionTitle: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 26,
    color: colors.textDark,
    flex: 1,
  },
  viewAll: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 18,
    color: colors.primary,
  },
});
