import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  bg: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  card: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#FFF8E8',
    borderRadius: 32,
    borderWidth: 1.5,
    borderColor: 'rgba(196,138,74,0.35)',
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 28,
    alignItems: 'center',
    shadowColor: '#3D2008',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  art: {
    width: 180,
    height: 180,
    marginTop: 4,
    marginBottom: 8,
  },
  title: {
    fontFamily: 'Fredoka-Bold',
    fontSize: 32,
    color: '#3B210F',
    textAlign: 'center',
    marginBottom: 10,
  },
  body: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 19,
    color: '#6B4A2A',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 6,
  },
  parentNote: {
    fontFamily: 'Fredoka-Regular',
    fontSize: 16,
    color: '#8E6C46',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 18,
  },
  usagePill: {
    backgroundColor: '#FCEFD2',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 7,
    marginBottom: 22,
  },
  usagePillText: {
    fontFamily: 'Fredoka-SemiBold',
    fontSize: 15,
    color: '#A06000',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 30,
    alignSelf: 'stretch',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: colors.primaryDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  primaryButtonText: {
    fontFamily: 'Fredoka-Bold',
    color: '#FFFFFF',
    fontSize: 19,
  },
  secondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 30,
    alignSelf: 'stretch',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,154,46,0.55)',
    backgroundColor: 'transparent',
  },
  secondaryButtonText: {
    fontFamily: 'Fredoka-SemiBold',
    color: colors.primaryDark,
    fontSize: 17,
  },
});
