export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PACKS: '/packs',
  PACK_NEW: '/packs/new',
  PACK_EDIT: '/packs/:packId',
  MODELS: '/models',
  MODEL_NEW: '/models/new',
  MODEL_EDIT: '/models/:wordKey',
  USERS: '/users',
  USER_DETAIL: '/users/:uid',
  ANALYTICS: '/analytics',
  ANALYTICS_SAVED_WORDS: '/analytics/saved-words',
  ANALYTICS_SCREEN_TIME: '/analytics/screen-time',
  ANALYTICS_ACHIEVEMENTS: '/analytics/achievements',
  ANALYTICS_GAMES: '/analytics/games',
  ANALYTICS_FLAGGED_EVENTS: '/analytics/flagged-events',
  MODERATION: '/moderation',
  NOTIFICATIONS: '/notifications',
  APP_CONFIG: '/config',
  REVENUE: '/revenue',
  FEEDBACK: '/feedback',
  WISHLIST: '/wishlist',
} as const;
